name: Auto update translator metadata
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # copy git 仓库到虚拟机上
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    
    - name: Git init
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git clean -f  # Remove untrack file

    - name: Update metadata
      id: update_metadata
      run: |
        python metadata.py
#     - name: Git commit
#       uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
#       with:
#         # The arguments for the `git add` command (see the paragraph below for more info)
#         add: 'data/translators.json'
#         message: 'Update translators.json'
#         push: true
    - name: Git status
      run: |
        git status
        remote_addr=`git remote get-url --push origin`
        remote_addr=`echo $remote_addr|  awk -F'://' '{print $2}'`
        remote_addr=https://${user_name}:${{ secrets.GITHUB_TOKEN }}@${remote_addr}
        echo ${remote_addr}
        #git remote add origin ${remote_addr}
        #git push origin HEAD:gh-pages --force



