name: Auto update translator metadata
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # copy git 仓库到虚拟机上
    - name: 'Checkout codes'
      uses: actions/checkout@v3
    
    - name: Git init
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git clean -f  # Remove untrack file

    - name: Update metadata
      id: update_metadata
      run: |
        python metadata.py
      
    - name: check update
      id: modified
      run: |
        
        counts=`git status | grep "data/translators.json" | wc -l`
        echo "counts=${counts}" >> $GITHUB_ENV

    - name: Git status
      if: env.counts == 1
      run: |
        git status
        echo ${{ env.counts }}
        git add data/translators.json
        git commit -m 'update translator metadata'
        git push





